# Metadata for your course

title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: # the name of the repository when it is created for the learner
  repo: # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type:     createIssue # the type of action, full list at https://lab.github.com/docs/actions/
  title: Welcome        # some actions require additional options, those should appear below `type:`
  body: welcome-text.md
                # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title:  Create a new pull request       # the title of the step, shown to the learner in the course progress page
  description: description: Add your name to the README.md file in your new pull request    # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  event:   pull_request.opened       # a list of the actions that will occur when the step is triggered by an event
  actions:
  - type:   gate      # the type of action, full list at https://lab.github.com/docs/actions
    left: '%payload.pull_request.title%'              # some actions require additional options, those should appear below `type:`
    operator: ===          # you can execute multiple actions in the `before` block
    right: Add name to README         #
   # - type: respond
   with: pr-opened.md
     
  #
  # - type:
  #   option:
